## <center>Linear Regression (Multiple Variable)<center>

## Topics

<ul>
    <li>Data Preprocessing: Handling NA Values</li>
    <li>Linear Regression Using Multiple Variables</li>

</ul>

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [14]:
data = "/Users/rajkumarnattamaisubramanian/Desktop/homeprices_multivariate.csv"
df = pd.read_csv(data)

In [15]:
#loading data into a dataframe
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [16]:
#now we have to handle the null

In [17]:
import math 
median_bedrooms = math.floor(df.bedrooms.median())

In [18]:
median_bedrooms

4

In [19]:
df.bedrooms #gives pandas series

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [20]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [21]:
#dataframe gets updated below 

df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [22]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [23]:
#now we have to create a linear regression object ones weare done with the preprocessing data step

In [24]:
reg = linear_model.LinearRegression()

In [25]:
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [26]:
reg.coef_ #these are the m1,m2, and m3 values

array([  112.06244194, 23388.88007794, -3231.71790863])

In [27]:
reg.intercept_ #this is the b value 

221323.00186540408

In [28]:
#1. 3000 square feet area, 3 bedrooms, 40 years old

reg.predict([[3000,3,40]])

array([498408.25158031])

In [29]:
#2. 2500 square feet area, 4 bedrooms, 5 year old

reg.predict([[2500,4,5]])

array([578876.03748933])

### The Multivariate Equation that predicts the house price in this case...

In [32]:
m1 = str(reg.coef_[0])
m2 = str(reg.coef_[1])
m3 = str(reg.coef_[2])
b = str(reg.intercept_)

In [40]:
print("price = "+ m1+ "*(area) + "+m2+"*(bedrooms) "+""+m3+"*(age) +"+b)

price = 112.06244194213458*(area) + 23388.88007793922*(bedrooms) -3231.7179086329634*(age) +221323.00186540408
